# Site settings
title: Steading System Software
email: your-email@domain.com
description: "Steading System Software: Independent System Software Consultants"
baseurl: ""
url: "http://www.steadingsoftware.com"

# Build settings
markdown: kramdown
permalink: pretty
